<a href="https://colab.research.google.com/github/AhmedRamadan433/Machine_Learning_Road/blob/main/testfolder/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[5,8,9,7,8,8],[1,2,11,4,5,6]])
arr

array([[ 5,  8,  9,  7,  8,  8],
       [ 1,  2, 11,  4,  5,  6]])

In [ ]:
ar=np.arange(2,25,5)
ar

array([ 2,  7, 12, 17, 22])

In [ ]:
np.ones((4,6),dtype=int).shape

(4, 6)

In [ ]:
np.random.randint(0,10,3)

array([0, 1, 7])

In [ ]:
arr.max(axis=0)

array([ 5,  8, 11,  7,  8,  8])

In [ ]:
arr.flatten()

array([ 5,  8,  9,  7,  8,  8,  1,  2, 11,  4,  5,  6])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
print(arr)
print(f"num of dimention : {arr.ndim}")
print(f"num of dimention : {arr.shape}")
print(f"num of dimention : {arr.size}")

[[ 5  8  9  7  8  8]
 [ 1  2 11  4  5  6]]
num of dimention : 2
num of dimention : (2, 6)
num of dimention : 12


In [ ]:
arr2=np.array([5,20,70,80,60,44])
arr2[::-3]

array([44, 70])

In [ ]:
print(arr)
arr[:,0]

[[ 5  8  9  7  8  8]
 [ 1  2 11  4  5  6]]


array([5, 1])

In [ ]:
l1=np.arange(1,10)
l1=l1[np.newaxis,np.newaxis,:]


In [ ]:
ll1=np.full((2,3),9)
ll2=np.full((2,3),5)
rs=np.concatenate((ll1.flatten(),ll2.flatten()))

In [ ]:
ll1

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
ll2

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
print(np.concatenate((ll1,ll2),axis=0))
print(np.concatenate((ll1,ll2),axis=1))

[[9 9 9]
 [9 9 9]
 [5 5 5]
 [5 5 5]]
[[9 9 9 5 5 5]
 [9 9 9 5 5 5]]


In [ ]:
theta=np.linspace(0,np.pi,5)
theta=np.degrees(theta)
theta

array([  0.,  45.,  90., 135., 180.])

In [ ]:
rnd=np.random.random(3)
rnd=np.degrees(rnd)
print(rnd)
print(np.cos(rnd))


[36.90978258 27.11568971 45.414699  ]
[ 0.70432162 -0.40058219  0.13795312]


In [ ]:
np.cos(theta)

array([ 1.        ,  0.52532199, -0.44807362, -0.99608784, -0.59846007])

In [ ]:
ar

array([ 2,  7, 12, 17, 22])

In [ ]:
np.add(5,ar,out=ar)
ar

array([ 7, 12, 17, 22, 27])